### ISSUE TITLE
Update repo with organization project updates. 

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/START_HERE#25]
A bunch of projects have been updated, we'd like to update this readme to reflect that.

**Comment by ssiddhantsharma** [comment]
@wimo7083 I will take this, where can I find those projects to be included!

**Comment by wimo7083** [comment]
Starting here:
We currently have:

## OperationCode Backend

## OperationCode Frontend

## Town Crier

## OperationCode Bot

## OperationCodePyBot

## OperationCode Slash Commands

## Opentroops Projects

New:

Keep Town Crier

plus: do these for the others:

![image](https://user-images.githubusercontent.com/10781353/47305622-48c79080-d5e7-11e8-9de2-bb0e76ed0382.png)

And make sure the links are correct. 

Thank you!

Assiging myself as a placeholder.

**Comment by wimo7083** [comment]
I don't quite follow. We can work on it together either way.

**Comment by Soundug** [comment]
@ssiddhantsharma No problem. Good luck. :)

**Comment by firmanslll** [comment]
semoga beehasil
