### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by ipatch** [OperationCode/START_HERE#38]
Hadn't messed around with Inkscape in a while, so I thought I take the current logo in the **README.md** and make it an SVG.  I traced the original raster PNG image using Inkscape and then pushed and pulled some nodes to get it to resemble the original logo, and tried to make the star a little more crispy and aligned.

Attached below is an SVG logo that can be opened in inkscape and a separate SVG file of the same logo that does not contain all the meta data that inkscape adds when working with an SVG in Inkscape.  Inkscape adds a couple of kilobytes in the overall file size, and unfortunately I couldn't get the SVG to a sub 3KB file size which is what the original PNG was when I downloaded it, but the plain SVG attached to this issue weighs in 🥊 at ~ 11KB.

Apparently github does not allow uploading of SVG files directly with github issues, so I compressed both svg images in a zip.

[operation-code-svg-logos.zip](https://github.com/OperationCode/START_HERE/files/3413981/operation-code-svg-logos.zip)

Also the SVG graphics can be seen and downloaded from here as well.

https://github.com/ipatch/homebrew-us-05/tree/dev/inkscape/my-vector-gfx

 cheers 🍻
Chris

**Comment by tristinDLC** [comment]
I'm not sure if you've been to our actual website, but we have a branding section that contains an EPS of all graphics. You can view all branding [here](https://operation-code-assets.s3.us-east-2.amazonaws.com/Operation-Code-Logo.eps).

No need to trace any logos, you could have just opened the EPS, cropped out the logo you wanted, and saved as an SVG.
