### ISSUE TITLE
include license

### ISSUE THREAD

**Issue by Parikshit-Hooda** [OperationCode/START_HERE#40]
include license file!
Happy to take this up as part of hactoberfest!

**Comment by parammittal16** [comment]
hi @Parikshit-Hooda I wanna take this issue

**Comment by niblux** [comment]
Hi all, 
 Eager to join in on Hactoberfest , i created a new branch and wanted to add the GPL license to @parammittal16 MIT license.

Was unable to push permission denied, do i need permission to push ?

Thank you.

**Comment by kylemh** [comment]
No need for a license in this repo as it is just documentation
